"""Enumerate the conditional delta-ten collision-profile ledger.

Under the four standing polynomial-normalization and finite-singularity
hypotheses, the normalized ``(4, 9)`` family has collision delta ten beyond
its forced ``T(2,5)`` cusp.  Every branch in those remaining finite
singularities is smooth.  This module enumerates the resulting *candidate*
collision profiles from two pieces of local data:

* a target fiber has two, three, or four normalization preimages, because
  ``P(t) - X`` has degree four; and
* the pairwise contacts of smooth plane branches form an integral contact
  tree.

The codimension attached to a profile is the multijet ``expected``
codimension.  It is not a claim that the corresponding stratum is nonempty,
has that actual codimension, or is irreducible in this special five-parameter
family.  Those questions require saturated incidence ideals and elimination.

The enumeration gives 35 non-node local atoms and 145 global profiles after
the unused delta is completed by ordinary nodes.  It deliberately keeps the
target-fiber grouping: the pair-length partition alone cannot distinguish ten
nodes from, for example, one ordinary triple point and seven nodes.
"""

from __future__ import annotations

from collections import Counter
from dataclasses import dataclass
from enum import IntEnum
from functools import cache
from itertools import combinations, groupby, permutations, product
from math import comb
from typing import Final

from sympy import Expr, Matrix, Poly, expand, factor, gcd

from scripts.a6_delta_ten_generic import (
    ALPHA,
    BETA,
    COLLISION_POLYNOMIAL,
    DELTA,
    GAMMA,
    KAPPA,
    S,
)

COLLISION_DELTA_BUDGET: Final = 10
PARAMETER_SPACE_DIMENSION: Final = 5


class FiberKind(IntEnum):
    """Number of smooth normalization branches over one target point."""

    TWO_BRANCH = 2
    TRIPLE = 3
    QUADRUPLE = 4


def _branch_edges(branch_count: int) -> tuple[tuple[int, int], ...]:
    """Return lexicographically ordered pairs of branch indices."""

    return tuple(combinations(range(branch_count), 2))


def _contact_dictionary(
    branch_count: int,
    contacts: tuple[int, ...],
) -> dict[tuple[int, int], int]:
    """Pair the contact tuple with the standard branch-edge ordering."""

    edges = _branch_edges(branch_count)
    if len(contacts) != len(edges):
        msg = "the contact tuple has the wrong number of branch pairs"
        raise ValueError(msg)
    return dict(zip(edges, contacts, strict=True))


def contact_profile_is_ultrametric(
    branch_count: int,
    contacts: tuple[int, ...],
) -> bool:
    """Whether every triple has its two smallest contacts equal.

    For graph branches, ``ord(f_i - f_j)`` has this property.  It is the
    finite contact-tree compatibility condition used by this ledger.
    """

    if branch_count < 2 or any(contact < 1 for contact in contacts):
        return False
    try:
        contact_by_edge = _contact_dictionary(branch_count, contacts)
    except ValueError:
        return False
    for triple in combinations(range(branch_count), 3):
        triple_contacts = sorted(
            contact_by_edge[_ordered_edge(left, right)]
            for left, right in combinations(triple, 2)
        )
        if triple_contacts[0] != triple_contacts[1]:
            return False
    return True


def _component_count(
    branch_count: int,
    active_edges: tuple[tuple[int, int], ...],
) -> int:
    """Count blocks in the equivalence relation generated by active edges."""

    parents = list(range(branch_count))

    def root(index: int) -> int:
        while parents[index] != index:
            parents[index] = parents[parents[index]]
            index = parents[index]
        return index

    for left, right in active_edges:
        left_root = root(left)
        right_root = root(right)
        if left_root != right_root:
            parents[right_root] = left_root
    return len({root(index) for index in range(branch_count)})


def expected_contact_tree_codimension(
    branch_count: int,
    contacts: tuple[int, ...],
) -> int:
    """Return the expected multijet codimension of one target fiber.

    The base ``branch_count - 2`` is the expected codimension of an ordinary
    ``branch_count``-fold target fiber after its source parameters move.  At
    jet level ``level``, branches with contact greater than ``level`` must
    have equal coefficients.  A block of size ``m`` contributes ``m - 1``
    further conditions.

    This is a combinatorial expectation, not an assertion of transversality
    for the normalized delta-ten family.
    """

    if not contact_profile_is_ultrametric(branch_count, contacts):
        msg = "contacts must form an integral smooth-branch contact tree"
        raise ValueError(msg)
    edges = _branch_edges(branch_count)
    extra = 0
    for level in range(1, max(contacts)):
        active_edges = tuple(
            edge
            for edge, contact in zip(edges, contacts, strict=True)
            if contact > level
        )
        extra += branch_count - _component_count(branch_count, active_edges)
    return branch_count - 2 + extra


@dataclass(frozen=True, slots=True)
class LocalAtom:
    """One candidate finite target fiber with smooth local branches."""

    name: str
    kind: FiberKind
    contacts: tuple[int, ...]
    delta: int
    expected_codimension: int

    def __post_init__(self) -> None:
        branch_count = int(self.kind)
        if len(self.contacts) != comb(branch_count, 2):
            msg = "a local atom must record every pairwise contact"
            raise ValueError(msg)
        if self.delta != sum(self.contacts):
            msg = "a smooth-branch atom's delta is the sum of its contacts"
            raise ValueError(msg)
        expected = expected_contact_tree_codimension(
            branch_count,
            self.contacts,
        )
        if self.expected_codimension != expected:
            msg = "the stored expected codimension disagrees with its contact tree"
            raise ValueError(msg)

    @property
    def pair_length_partition(self) -> tuple[int, ...]:
        """Pair-scheme lengths, forgetting their common target grouping."""

        return tuple(sorted(self.contacts, reverse=True))


def _atom_key(atom: LocalAtom) -> tuple[int, int, int, str]:
    """Canonical local-atom order used by the multiset enumeration."""

    return (
        int(atom.kind),
        atom.expected_codimension,
        atom.delta,
        atom.name,
    )


def _two_branch_atoms() -> tuple[LocalAtom, ...]:
    """Return the nine contacts ``C2`` through ``C10``."""

    return tuple(
        LocalAtom(
            name=f"C{contact}",
            kind=FiberKind.TWO_BRANCH,
            contacts=(contact,),
            delta=contact,
            expected_codimension=contact - 1,
        )
        for contact in range(2, COLLISION_DELTA_BUDGET + 1)
    )


def _triple_atoms() -> tuple[LocalAtom, ...]:
    """Return all profiles ``(q,q,k)`` with ``2*q + k <= 10``."""

    result: list[LocalAtom] = []
    for repeated_contact in range(1, COLLISION_DELTA_BUDGET + 1):
        for largest_contact in range(
            repeated_contact,
            COLLISION_DELTA_BUDGET + 1,
        ):
            contacts = (
                repeated_contact,
                repeated_contact,
                largest_contact,
            )
            delta = sum(contacts)
            if delta > COLLISION_DELTA_BUDGET:
                break
            result.append(
                LocalAtom(
                    name=(f"T{repeated_contact}{repeated_contact}{largest_contact}"),
                    kind=FiberKind.TRIPLE,
                    contacts=contacts,
                    delta=delta,
                    expected_codimension=expected_contact_tree_codimension(
                        3,
                        contacts,
                    ),
                )
            )
    return tuple(result)


QUADRUPLE_EDGES: Final = _branch_edges(4)
QUADRUPLE_EDGE_INDEX: Final = {
    edge: index for index, edge in enumerate(QUADRUPLE_EDGES)
}
QUADRUPLE_RELABELINGS: Final = tuple(permutations(range(4)))


def _ordered_edge(left: int, right: int) -> tuple[int, int]:
    """Return an edge in increasing endpoint order."""

    return (left, right) if left < right else (right, left)


def _relabel_quadruple_contacts(
    contacts: tuple[int, ...],
    relabeling: tuple[int, ...],
) -> tuple[int, ...]:
    """Relabel a quadruple contact matrix in standard edge order."""

    return tuple(
        contacts[
            QUADRUPLE_EDGE_INDEX[_ordered_edge(relabeling[left], relabeling[right])]
        ]
        for left, right in QUADRUPLE_EDGES
    )


def _canonical_quadruple_contacts(
    contacts: tuple[int, ...],
) -> tuple[int, ...]:
    """Canonicalize a contact matrix under the 24 branch relabelings."""

    return min(
        _relabel_quadruple_contacts(contacts, relabeling)
        for relabeling in QUADRUPLE_RELABELINGS
    )


def _quadruple_name(contacts: tuple[int, ...]) -> str:
    """Name one of the eleven delta-at-most-ten quadruple contact trees."""

    elevated = tuple(sorted(contact for contact in contacts if contact > 1))
    if not elevated:
        return "Q0"
    if len(elevated) == 1:
        return f"Q{elevated[0]}"
    if len(elevated) == 2:
        return f"Q{elevated[0]}|{elevated[1]}"
    if len(elevated) == 3 and elevated[:2] == (2, 2):
        return f"Q[22{elevated[2]}]"
    msg = "unexpected quadruple contact tree within delta ten"
    raise ValueError(msg)


def _quadruple_atoms() -> tuple[LocalAtom, ...]:
    """Enumerate all integral four-branch contact trees of delta at most ten."""

    canonical_profiles: set[tuple[int, ...]] = set()
    # Six positive pair contacts can have no entry above five when their sum
    # is at most ten.
    for contacts in product(range(1, 6), repeat=len(QUADRUPLE_EDGES)):
        if sum(contacts) > COLLISION_DELTA_BUDGET:
            continue
        if not contact_profile_is_ultrametric(4, contacts):
            continue
        canonical_profiles.add(_canonical_quadruple_contacts(contacts))

    atoms = tuple(
        LocalAtom(
            name=_quadruple_name(contacts),
            kind=FiberKind.QUADRUPLE,
            contacts=contacts,
            delta=sum(contacts),
            expected_codimension=expected_contact_tree_codimension(
                4,
                contacts,
            ),
        )
        for contacts in canonical_profiles
    )
    return tuple(sorted(atoms, key=_atom_key))


@cache
def local_atoms() -> tuple[LocalAtom, ...]:
    """Return all 35 non-node local target-fiber candidates."""

    atoms = _two_branch_atoms() + _triple_atoms() + _quadruple_atoms()
    return tuple(sorted(atoms, key=_atom_key))


@dataclass(frozen=True, slots=True)
class GlobalProfile:
    """A multiset of non-node atoms, completed to delta ten by nodes."""

    atoms: tuple[LocalAtom, ...]

    def __post_init__(self) -> None:
        if self.atoms != tuple(sorted(self.atoms, key=_atom_key)):
            msg = "global-profile atoms must be in canonical order"
            raise ValueError(msg)
        if self.non_node_delta > COLLISION_DELTA_BUDGET:
            msg = "a global profile exceeds the collision-delta budget"
            raise ValueError(msg)

    @property
    def non_node_delta(self) -> int:
        """Delta consumed by non-node target fibers."""

        return sum(atom.delta for atom in self.atoms)

    @property
    def node_count(self) -> int:
        """Number of ordinary nodes completing the delta-ten budget."""

        return COLLISION_DELTA_BUDGET - self.non_node_delta

    @property
    def expected_codimension(self) -> int:
        """Additive expected codimension of distinct target fibers."""

        return sum(atom.expected_codimension for atom in self.atoms)

    @property
    def pair_length_partition(self) -> tuple[int, ...]:
        """Length partition after forgetting which pairs share a target."""

        contacts = [contact for atom in self.atoms for contact in atom.contacts]
        contacts.extend([1] * self.node_count)
        return tuple(sorted(contacts, reverse=True))

    @property
    def name(self) -> str:
        """Compact canonical name, with ``N`` denoting an ordinary node."""

        terms: list[str] = []
        for atom, repeated_atoms in groupby(self.atoms):
            multiplicity = sum(1 for _ in repeated_atoms)
            terms.append(
                atom.name if multiplicity == 1 else f"{atom.name}^{multiplicity}"
            )
        if self.node_count:
            terms.append("N" if self.node_count == 1 else f"{self.node_count}N")
        return " + ".join(terms)


@cache
def global_profiles() -> tuple[GlobalProfile, ...]:
    """Enumerate every multiset of atoms with total delta at most ten."""

    atoms = local_atoms()
    result: list[GlobalProfile] = [GlobalProfile(())]

    def extend(
        first_index: int,
        chosen: tuple[LocalAtom, ...],
        used_delta: int,
    ) -> None:
        for index in range(first_index, len(atoms)):
            atom = atoms[index]
            next_delta = used_delta + atom.delta
            if next_delta > COLLISION_DELTA_BUDGET:
                continue
            next_chosen = (*chosen, atom)
            result.append(GlobalProfile(next_chosen))
            extend(index, next_chosen, next_delta)

    extend(0, (), 0)
    return tuple(sorted(result, key=lambda profile: profile.name))


def profiles_with_expected_codimension(
    expected_codimension: int,
) -> tuple[GlobalProfile, ...]:
    """Select profiles by combinatorial expected codimension."""

    if expected_codimension < 0:
        msg = "expected codimension must be nonnegative"
        raise ValueError(msg)
    return tuple(
        profile
        for profile in global_profiles()
        if profile.expected_codimension == expected_codimension
    )


def expected_codimension_histogram() -> tuple[int, ...]:
    """Return counts indexed by expected codimension zero through nine."""

    histogram = Counter(profile.expected_codimension for profile in global_profiles())
    return tuple(histogram.get(codimension, 0) for codimension in range(10))


COEFFICIENT_PARAMETERS: Final = (ALPHA, BETA, GAMMA, DELTA)
COEFFICIENT_SLICE_MINOR_ROWS: Final = (
    (4, 6, 7, 8),
    (3, 6, 7, 8),
)


@cache
def coefficient_slice_rank_certificate() -> tuple[Expr, Expr, Expr]:
    """Return two everywhere-covering coefficient minors and their monic gcd.

    For fixed ``k``, the collision-decic coefficients are affine-linear in
    ``(a,b,c,d)``.  The two minors show that this linear coefficient map has
    rank four for every complex ``k``.  This supports a future coefficient-
    image elimination; it does not realize or exclude any collision profile.
    """

    expanded_collision = expand(COLLISION_POLYNOMIAL)
    coefficient_matrix = Matrix(
        [
            [
                expanded_collision.coeff(S, degree).coeff(parameter)
                for parameter in COEFFICIENT_PARAMETERS
            ]
            for degree in range(COLLISION_DELTA_BUDGET)
        ]
    )
    first_minor: Expr = factor(
        coefficient_matrix[list(COEFFICIENT_SLICE_MINOR_ROWS[0]), :].det()
    )
    second_minor: Expr = factor(
        coefficient_matrix[list(COEFFICIENT_SLICE_MINOR_ROWS[1]), :].det()
    )
    common_divisor: Poly = gcd(
        Poly(first_minor, KAPPA),
        Poly(second_minor, KAPPA),
    ).monic()
    common_divisor_expression: Expr = common_divisor.as_expr()
    return first_minor, second_minor, common_divisor_expression


EXPECTED_ATOM_KIND_COUNTS: Final = (
    (FiberKind.TWO_BRANCH, 9),
    (FiberKind.TRIPLE, 15),
    (FiberKind.QUADRUPLE, 11),
)
EXPECTED_ATOM_NAMES_BY_KIND: Final = (
    (
        FiberKind.TWO_BRANCH,
        tuple(sorted(f"C{contact}" for contact in range(2, 11))),
    ),
    (
        FiberKind.TRIPLE,
        tuple(
            sorted(
                (
                    "T111",
                    "T112",
                    "T113",
                    "T114",
                    "T115",
                    "T116",
                    "T117",
                    "T118",
                    "T222",
                    "T223",
                    "T224",
                    "T225",
                    "T226",
                    "T333",
                    "T334",
                )
            )
        ),
    ),
    (
        FiberKind.QUADRUPLE,
        tuple(
            sorted(
                (
                    "Q0",
                    "Q2",
                    "Q3",
                    "Q4",
                    "Q5",
                    "Q2|2",
                    "Q2|3",
                    "Q2|4",
                    "Q3|3",
                    "Q[222]",
                    "Q[223]",
                )
            )
        ),
    ),
)
EXPECTED_CODIMENSION_HISTOGRAM: Final = (
    1,
    2,
    6,
    14,
    29,
    38,
    32,
    16,
    6,
    1,
)
EXPECTED_CODIMENSION_ONE_NAMES: Final = (
    "C2 + 8N",
    "T111 + 7N",
)
EXPECTED_CODIMENSION_TWO_NAMES: Final = tuple(
    sorted(
        (
            "C3 + 7N",
            "C2^2 + 6N",
            "T112 + 6N",
            "C2 + T111 + 5N",
            "Q0 + 4N",
            "T111^2 + 4N",
        )
    )
)


@dataclass(frozen=True, slots=True)
class PartitionLedgerCertificate:
    """Checksums for the finite combinatorial candidate ledger."""

    atom_kind_counts: tuple[tuple[FiberKind, int], ...]
    atom_names_by_kind: tuple[tuple[FiberKind, tuple[str, ...]], ...]
    profile_count: int
    codimension_histogram: tuple[int, ...]
    codimension_one_names: tuple[str, ...]
    codimension_two_names: tuple[str, ...]
    endpoint_count: int
    overdetermined_count: int
    coefficient_slice_minors: tuple[Expr, Expr]
    coefficient_slice_minor_gcd: Expr

    @property
    def verified(self) -> bool:
        """Whether all exact combinatorial and coefficient checks agree."""

        return bool(
            self.atom_kind_counts == EXPECTED_ATOM_KIND_COUNTS
            and self.atom_names_by_kind == EXPECTED_ATOM_NAMES_BY_KIND
            and sum(count for _, count in self.atom_kind_counts) == 35
            and self.profile_count == 145
            and self.codimension_histogram == EXPECTED_CODIMENSION_HISTOGRAM
            and self.codimension_one_names == EXPECTED_CODIMENSION_ONE_NAMES
            and self.codimension_two_names == EXPECTED_CODIMENSION_TWO_NAMES
            and self.endpoint_count == 38
            and self.overdetermined_count == 55
            and self.coefficient_slice_minors[0] == 256 * KAPPA
            and (self.coefficient_slice_minors[1] - 128 * (3 * KAPPA**2 + 4)).expand()
            == 0
            and self.coefficient_slice_minor_gcd == 1
        )


@cache
def exact_partition_ledger_certificate() -> PartitionLedgerCertificate:
    """Build the exact delta-ten candidate-ledger certificate."""

    atoms = local_atoms()
    profiles = global_profiles()
    kind_counts = Counter(atom.kind for atom in atoms)
    first_minor, second_minor, minor_gcd = coefficient_slice_rank_certificate()
    return PartitionLedgerCertificate(
        atom_kind_counts=tuple((kind, kind_counts.get(kind, 0)) for kind in FiberKind),
        atom_names_by_kind=tuple(
            (
                kind,
                tuple(sorted(atom.name for atom in atoms if atom.kind == kind)),
            )
            for kind in FiberKind
        ),
        profile_count=len(profiles),
        codimension_histogram=expected_codimension_histogram(),
        codimension_one_names=tuple(
            profile.name for profile in profiles_with_expected_codimension(1)
        ),
        codimension_two_names=tuple(
            profile.name for profile in profiles_with_expected_codimension(2)
        ),
        endpoint_count=len(profiles_with_expected_codimension(5)),
        overdetermined_count=sum(
            profile.expected_codimension > PARAMETER_SPACE_DIMENSION
            for profile in profiles
        ),
        coefficient_slice_minors=(first_minor, second_minor),
        coefficient_slice_minor_gcd=minor_gcd,
    )


def main() -> int:
    """Print the candidate ledger and its explicit claim boundary."""

    certificate = exact_partition_ledger_certificate()
    print("local atom counts:", certificate.atom_kind_counts)
    print("global profiles:", certificate.profile_count)
    print("expected-codimension histogram:", certificate.codimension_histogram)
    print("expected divisors:", certificate.codimension_one_names)
    print("expected codimension-two profiles:", certificate.codimension_two_names)
    print(
        "expected endpoints:",
        tuple(profile.name for profile in profiles_with_expected_codimension(5)),
    )
    print(
        "overdetermined candidates needing elimination:",
        certificate.overdetermined_count,
    )
    print("coefficient-slice rank minors:", certificate.coefficient_slice_minors)
    print("delta-ten partition ledger verified:", certificate.verified)
    print(
        "claim boundary: codimensions are combinatorial expectations; "
        "realization and exclusion require saturated elimination"
    )
    return 0 if certificate.verified else 1


if __name__ == "__main__":
    raise SystemExit(main())
