"""Exact finite-group certificate for the six-sheet Jacobian frontier.

For a separable extension ``L/K`` of degree six, let ``M`` be its normal
closure, ``G = Gal(M/K)``, and ``H = Gal(M/L)``.  The faithful action of
``G`` on ``G/H`` is one of GAP's sixteen transitive groups of degree six.

This module stores the generators returned by GAP 4.14.0 for ``6T1`` through
``6T16`` and independently recomputes the invariants used in the research
argument with a small, dependency-free permutation engine.  It deliberately
does *not* assert that every abstract candidate is realizable by a Keller
map; the certificate only identifies what finite group theory can exclude.
"""

from __future__ import annotations

from collections.abc import Iterable, Sequence
from dataclasses import dataclass
from itertools import combinations, combinations_with_replacement, product
from typing import Final, TypeAlias

Permutation: TypeAlias = tuple[int, ...]
PermutationGroup: TypeAlias = frozenset[Permutation]
Block: TypeAlias = frozenset[int]
CycleType: TypeAlias = tuple[int, ...]

DEGREE: Final = 6
IDENTITY: Final[Permutation] = tuple(range(DEGREE))
OREVKOV_SIX_SHEET_BUDGET: Final = DEGREE - 1
OREVKOV_FORBIDDEN_RAMIFICATION_INDEX: Final = DEGREE - 1
OREVKOV_ONE_DICRITICAL_TYPES: Final[frozenset[CycleType]] = frozenset(
    {
        (2, 1, 1, 1, 1),
        (2, 2, 1, 1),
        (3, 1, 1, 1),
        (4, 1, 1),
    }
)


def _from_cycles(*cycles: tuple[int, ...]) -> Permutation:
    """Build a permutation from disjoint cycles written with GAP's 1-based points."""

    image = list(IDENTITY)
    support: set[int] = set()
    for cycle in cycles:
        if len(cycle) < 2:
            msg = "cycles must contain at least two points"
            raise ValueError(msg)
        zero_based = tuple(point - 1 for point in cycle)
        if any(point < 0 or point >= DEGREE for point in zero_based):
            msg = f"cycle point outside 1..{DEGREE}"
            raise ValueError(msg)
        if support.intersection(zero_based):
            msg = "cycles must be disjoint"
            raise ValueError(msg)
        support.update(zero_based)
        for source, target in zip(zero_based, zero_based[1:] + zero_based[:1]):
            image[source] = target
    return tuple(image)


# Hostile stopping fixture for the one-dicritical A6 local analysis.  The two
# 3-cycles satisfy the meridional T(2,5) five-braid relation and generate A5 on
# five sheets; adjoining the collision 3-cycle generates A6 on all six.  Thus
# the forced local (2,5) cusp is not excluded by abstract monodromy alone.
A6_TORUS_2_5_LOCAL_GENERATORS: Final[tuple[Permutation, Permutation]] = (
    _from_cycles((3, 4, 5)),
    _from_cycles((1, 2, 3)),
)
A6_COLLISION_MERIDIAN: Final[Permutation] = _from_cycles((4, 5, 6))

# Hostile stopping fixture for the saturated two-curve S6 passport.  The first
# pair models a 3+3 self-collision and the second pair a 2+2 self-collision.
# Each pair has disjoint support, but all four meridians together generate S6.
S6_TWO_CURVE_COLLISION_GENERATORS: Final[tuple[Permutation, ...]] = (
    _from_cycles((1, 2, 3)),
    _from_cycles((4, 5, 6)),
    _from_cycles((1, 4)),
    _from_cycles((2, 5)),
)


def compose(left: Permutation, right: Permutation) -> Permutation:
    """Return ``left ∘ right``."""

    return tuple(left[right[point]] for point in range(DEGREE))


def inverse(permutation: Permutation) -> Permutation:
    """Return the inverse of a permutation."""

    result = [0] * DEGREE
    for source, target in enumerate(permutation):
        result[target] = source
    return tuple(result)


def generated_group(generators: Iterable[Permutation]) -> PermutationGroup:
    """Enumerate the finite subgroup generated by ``generators`` exactly."""

    generator_tuple = tuple(generators)
    if not generator_tuple:
        return frozenset({IDENTITY})
    seen = {IDENTITY}
    frontier = [IDENTITY]
    while frontier:
        element = frontier.pop()
        for generator in generator_tuple:
            candidate = compose(element, generator)
            if candidate not in seen:
                seen.add(candidate)
                frontier.append(candidate)
    return frozenset(seen)


@dataclass(frozen=True)
class TransitiveGroupFixture:
    """A GAP transitive-group identifier, description, and exact generators."""

    identifier: str
    structure: str
    generators: tuple[Permutation, ...]


# Exported by:
#   List([1..NrTransitiveGroups(6)], i ->
#     GeneratorsOfGroup(TransitiveGroup(6, i)));
# GAP 4.14.0 reports NrTransitiveGroups(6) = 16.
TRANSITIVE_GROUPS: Final[tuple[TransitiveGroupFixture, ...]] = (
    TransitiveGroupFixture("6T1", "C6", (_from_cycles((1, 2, 3, 4, 5, 6)),)),
    TransitiveGroupFixture(
        "6T2",
        "S3",
        (_from_cycles((1, 3, 5), (2, 4, 6)), _from_cycles((1, 4), (2, 3), (5, 6))),
    ),
    TransitiveGroupFixture(
        "6T3",
        "D12",
        (_from_cycles((1, 2, 3, 4, 5, 6)), _from_cycles((1, 4), (2, 3), (5, 6))),
    ),
    TransitiveGroupFixture(
        "6T4",
        "A4",
        (_from_cycles((1, 4), (2, 5)), _from_cycles((1, 3, 5), (2, 4, 6))),
    ),
    TransitiveGroupFixture(
        "6T5",
        "C3 x S3",
        (_from_cycles((2, 4, 6)), _from_cycles((1, 4), (2, 5), (3, 6))),
    ),
    TransitiveGroupFixture(
        "6T6",
        "C2 x A4",
        (_from_cycles((3, 6)), _from_cycles((1, 3, 5), (2, 4, 6))),
    ),
    TransitiveGroupFixture(
        "6T7",
        "S4",
        (
            _from_cycles((1, 4), (2, 5)),
            _from_cycles((1, 3, 5), (2, 4, 6)),
            _from_cycles((1, 5), (2, 4)),
        ),
    ),
    TransitiveGroupFixture(
        "6T8",
        "S4",
        (
            _from_cycles((1, 4), (2, 5)),
            _from_cycles((1, 3, 5), (2, 4, 6)),
            _from_cycles((1, 5), (2, 4), (3, 6)),
        ),
    ),
    TransitiveGroupFixture(
        "6T9",
        "S3 x S3",
        (
            _from_cycles((2, 4, 6)),
            _from_cycles((1, 5), (2, 4)),
            _from_cycles((1, 4), (2, 5), (3, 6)),
        ),
    ),
    TransitiveGroupFixture(
        "6T10",
        "(C3 x C3) : C4",
        (
            _from_cycles((2, 4, 6)),
            _from_cycles((1, 5), (2, 4)),
            _from_cycles((1, 4, 5, 2), (3, 6)),
        ),
    ),
    TransitiveGroupFixture(
        "6T11",
        "C2 x S4",
        (
            _from_cycles((3, 6)),
            _from_cycles((1, 3, 5), (2, 4, 6)),
            _from_cycles((1, 5), (2, 4)),
        ),
    ),
    TransitiveGroupFixture(
        "6T12",
        "A5",
        (_from_cycles((1, 2, 3, 4, 6)), _from_cycles((1, 4), (5, 6))),
    ),
    TransitiveGroupFixture(
        "6T13",
        "(S3 x S3) : C2",
        (
            _from_cycles((2, 4, 6)),
            _from_cycles((2, 4)),
            _from_cycles((1, 4), (2, 5), (3, 6)),
        ),
    ),
    TransitiveGroupFixture(
        "6T14",
        "S5",
        (_from_cycles((1, 2, 3, 4, 6)), _from_cycles((1, 2), (3, 4), (5, 6))),
    ),
    TransitiveGroupFixture(
        "6T15",
        "A6",
        (_from_cycles((1, 2, 3, 4, 5)), _from_cycles((4, 5, 6))),
    ),
    TransitiveGroupFixture(
        "6T16",
        "S6",
        (_from_cycles((1, 2, 3, 4, 5, 6)), _from_cycles((1, 2))),
    ),
)


def point_stabilizer(group: PermutationGroup, point: int = 0) -> PermutationGroup:
    """Return the stabilizer of ``point``."""

    return frozenset(element for element in group if element[point] == point)


def conjugate(element: Permutation, subgroup_element: Permutation) -> Permutation:
    """Return ``element * subgroup_element * element^-1``."""

    return compose(compose(element, subgroup_element), inverse(element))


def normalizer(group: PermutationGroup, subgroup: PermutationGroup) -> PermutationGroup:
    """Return the normalizer of ``subgroup`` inside ``group``."""

    return frozenset(
        element
        for element in group
        if frozenset(conjugate(element, member) for member in subgroup) == subgroup
    )


def is_transitive(group: PermutationGroup) -> bool:
    """Whether the orbit of the first point is all six points."""

    return {element[0] for element in group} == set(range(DEGREE))


def has_fixed_point(permutation: Permutation) -> bool:
    """Whether ``permutation`` fixes at least one of the six sheets."""

    return any(permutation[point] == point for point in range(DEGREE))


def cycle_type(permutation: Permutation) -> CycleType:
    """Return the complete cycle partition, including fixed points."""

    visited: set[int] = set()
    lengths: list[int] = []
    for starting_point in range(DEGREE):
        if starting_point in visited:
            continue
        point = starting_point
        length = 0
        while point not in visited:
            visited.add(point)
            point = permutation[point]
            length += 1
        lengths.append(length)
    return tuple(sorted(lengths, reverse=True))


@dataclass(frozen=True)
class ConjugacyClassAnalysis:
    """Cycle data and exact normal closure of one conjugacy class."""

    representative: Permutation
    cycle_type: CycleType
    class_size: int
    normal_closure_order: int

    @property
    def moved_sheet_count(self) -> int:
        """Return the number of sheets moved by a class representative.

        For a generic branch meridian this is also the minimum contribution
        ``sum(e*d)`` forced by the tangentially refined Orevkov identity.
        """

        return sum(length for length in self.cycle_type if length > 1)

    @property
    def avoids_forbidden_index(self) -> bool:
        """Whether no cycle requires Orevkov's forbidden index ``N - 1``."""

        return OREVKOV_FORBIDDEN_RAMIFICATION_INDEX not in self.cycle_type


def conjugacy_class_analyses(group: PermutationGroup) -> tuple[ConjugacyClassAnalysis, ...]:
    """Enumerate classes separately even when they have the same cycle type."""

    remaining = set(group)
    result: list[ConjugacyClassAnalysis] = []
    while remaining:
        representative = min(remaining)
        conjugacy_class = frozenset(
            conjugate(element, representative) for element in group
        )
        result.append(
            ConjugacyClassAnalysis(
                representative=representative,
                cycle_type=cycle_type(representative),
                class_size=len(conjugacy_class),
                normal_closure_order=len(generated_group(conjugacy_class)),
            )
        )
        remaining.difference_update(conjugacy_class)
    return tuple(
        sorted(
            result,
            key=lambda analysis: (
                analysis.cycle_type,
                analysis.class_size,
                analysis.normal_closure_order,
                analysis.representative,
            ),
        )
    )


def conjugacy_class(
    group: PermutationGroup,
    representative: Permutation,
) -> PermutationGroup:
    """Return the conjugacy class of ``representative`` inside ``group``."""

    if representative not in group:
        msg = "representative must belong to the group"
        raise ValueError(msg)
    return frozenset(conjugate(element, representative) for element in group)


def _integer_partitions(
    total: int,
    minimum_part: int = 1,
) -> tuple[tuple[int, ...], ...]:
    """Return nondecreasing positive partitions of ``total`` exactly once."""

    if total < 0:
        msg = "partition total must be nonnegative"
        raise ValueError(msg)
    if total == 0:
        return ((),)
    result: list[tuple[int, ...]] = []
    for first in range(minimum_part, total + 1):
        for tail in _integer_partitions(total - first, first):
            result.append((first, *tail))
    return tuple(result)


@dataclass(frozen=True)
class BranchInertiaRealization:
    """Dicritical components realizing one generic branch meridian.

    Each pair is ``(e, d)``: normal ramification index ``e`` and tangential
    degree ``d``.  One component contributes ``d`` disjoint ``e``-cycles to
    the meridian.  Orevkov's outer term starts at ``e``, while
    Riemann--Hurwitz forces at least ``e*(d-1)`` finite jump units.  Its true
    minimum contribution to the exact defect budget is therefore ``e*d``.
    """

    components: tuple[tuple[int, int], ...]

    @property
    def outer_sum_cost(self) -> int:
        """Return the unrefined ``sum(e)`` contribution."""

        return sum(index for index, _degree in self.components)

    @property
    def forced_tangential_jump(self) -> int:
        """Return the jump defect forced by finite tangential ramification."""

        return sum(
            index * (tangential_degree - 1)
            for index, tangential_degree in self.components
        )

    @property
    def ramification_cost(self) -> int:
        """Return the refined minimum ``sum(e*d)`` defect contribution."""

        return self.outer_sum_cost + self.forced_tangential_jump


def branch_inertia_realizations(
    partition: CycleType,
) -> tuple[BranchInertiaRealization, ...]:
    """Enumerate all component decompositions of a generic inertia cycle type.

    Fixed points do not require ramified dicritical components.  Repeated
    cycles of the same length may come either from one component of higher
    tangential degree or from several components over the same branch curve.
    """

    if sum(partition) != DEGREE or any(length < 1 for length in partition):
        msg = f"cycle type must be a partition of {DEGREE}"
        raise ValueError(msg)
    multiplicities: dict[int, int] = {}
    for length in partition:
        if length > 1:
            multiplicities[length] = multiplicities.get(length, 0) + 1
    if not multiplicities:
        return (BranchInertiaRealization(components=()),)

    choices_by_index: list[tuple[tuple[tuple[int, int], ...], ...]] = []
    for index, multiplicity in sorted(multiplicities.items()):
        choices_by_index.append(
            tuple(
                tuple((index, tangential_degree) for tangential_degree in degrees)
                for degrees in _integer_partitions(multiplicity)
            )
        )

    result = tuple(
        BranchInertiaRealization(
            components=tuple(
                component
                for same_index_components in choices
                for component in same_index_components
            )
        )
        for choices in product(*choices_by_index)
    )
    return tuple(
        sorted(
            result,
            key=lambda realization: (
                realization.ramification_cost,
                len(realization.components),
                realization.components,
            ),
        )
    )


@dataclass(frozen=True)
class InertiaClassPairAnalysis:
    """Joint normal-closure and minimum Orevkov cost of two branch classes."""

    first: ConjugacyClassAnalysis
    second: ConjugacyClassAnalysis
    joint_normal_closure_order: int

    @property
    def minimum_realizations(
        self,
    ) -> tuple[BranchInertiaRealization, BranchInertiaRealization]:
        """Return minimum-cost component realizations of the two classes."""

        return (
            branch_inertia_realizations(self.first.cycle_type)[0],
            branch_inertia_realizations(self.second.cycle_type)[0],
        )

    @property
    def minimum_ramification_cost(self) -> int:
        """Return the least refined defect cost before deck-forced components."""

        return sum(
            realization.ramification_cost
            for realization in self.minimum_realizations
        )


@dataclass(frozen=True)
class RamifiedBranchProfile:
    """Normally generating branch classes within the refined degree-six budget.

    Each entry of ``branch_classes`` represents a distinct irreducible target
    branch curve.  Dicritical components over the same target curve have
    already been combined into that meridian's disjoint cycles.
    """

    group_identifier: str
    branch_classes: tuple[ConjugacyClassAnalysis, ...]
    minimum_defect_cost: int

    @property
    def residual_defect(self) -> int:
        """Return the budget left for unramified dicriticals and excess jumps."""

        return OREVKOV_SIX_SHEET_BUDGET - self.minimum_defect_cost

    @property
    def survives_irreducible_branch_obstruction(self) -> bool:
        """Whether the sole-branch normalization obstruction leaves the profile.

        If there is just one ramified branch curve and its generic inertia moves
        more than half of the six sheets, a normalization collision would cost
        more than six sheets.  Its normalization is therefore injective.  The
        Lin--Zaidenberg local/global argument rules out that configuration.
        """

        return not (
            len(self.branch_classes) == 1
            and self.branch_classes[0].moved_sheet_count * 2 > DEGREE
        )


def ramified_branch_profiles(
    fixture: TransitiveGroupFixture,
) -> tuple[RamifiedBranchProfile, ...]:
    """Enumerate every normally generating ramified profile of cost at most five.

    Riemann--Hurwitz turns a generic meridian's moved-sheet count into its
    minimum Orevkov cost.  A fixed-point class containing a five-cycle is
    omitted because it requires a dicritical of index ``N - 1``, excluded by
    Orevkov's final remark.
    """

    group = generated_group(fixture.generators)
    candidates = tuple(
        analysis
        for analysis in conjugacy_class_analyses(group)
        if analysis.representative != IDENTITY
        and has_fixed_point(analysis.representative)
        and analysis.avoids_forbidden_index
    )
    result: list[RamifiedBranchProfile] = []
    # Every nontrivial inertia moves at least two sheets, so budget five permits
    # at most two distinct ramified target curves.
    for number_of_branches in (1, 2):
        for branch_classes in combinations_with_replacement(
            candidates,
            number_of_branches,
        ):
            minimum_defect_cost = sum(
                analysis.moved_sheet_count for analysis in branch_classes
            )
            if minimum_defect_cost > OREVKOV_SIX_SHEET_BUDGET:
                continue
            generated = generated_group(
                representative
                for analysis in branch_classes
                for representative in conjugacy_class(
                    group,
                    analysis.representative,
                )
            )
            if len(generated) != len(group):
                continue
            result.append(
                RamifiedBranchProfile(
                    group_identifier=fixture.identifier,
                    branch_classes=branch_classes,
                    minimum_defect_cost=minimum_defect_cost,
                )
            )
    return tuple(
        sorted(
            result,
            key=lambda profile: (
                profile.minimum_defect_cost,
                len(profile.branch_classes),
                tuple(
                    (
                        analysis.cycle_type,
                        analysis.class_size,
                        analysis.normal_closure_order,
                    )
                    for analysis in profile.branch_classes
                ),
            ),
        )
    )


def full_generating_inertia_pairs(
    fixture: TransitiveGroupFixture,
) -> tuple[InertiaClassPairAnalysis, ...]:
    """Return fixed-sheet class pairs whose joint normal closure is ``G``.

    Classes are not deduplicated by ambient cycle type.  This is essential for
    ``6T11``, which has two double-transposition classes with different normal
    closures.
    """

    group = generated_group(fixture.generators)
    allowed_classes = tuple(
        analysis
        for analysis in conjugacy_class_analyses(group)
        if analysis.cycle_type in OREVKOV_ONE_DICRITICAL_TYPES
    )
    result: list[InertiaClassPairAnalysis] = []
    for first, second in combinations_with_replacement(allowed_classes, 2):
        generated = generated_group(
            (
                *conjugacy_class(group, first.representative),
                *conjugacy_class(group, second.representative),
            )
        )
        if len(generated) == len(group):
            result.append(
                InertiaClassPairAnalysis(
                    first=first,
                    second=second,
                    joint_normal_closure_order=len(generated),
                )
            )
    return tuple(result)


@dataclass(frozen=True)
class OrevkovBudgetProfile:
    """A multiset of dicritical indices and the remaining finite jump defect."""

    dicritical_indices: tuple[int, ...]
    jump_defect: int


@dataclass(frozen=True)
class OneDicriticalPassport:
    """One exact group/class/ramification passport under one dicritical."""

    group_identifier: str
    group_structure: str
    automorphism_order: int
    ramification_index: int
    tangential_degree: int
    jump_defect: int
    inertia_class: ConjugacyClassAnalysis

    @property
    def forced_tangential_jump(self) -> int:
        """Return the part of ``jump_defect`` forced by tangential degree."""

        return self.ramification_index * (self.tangential_degree - 1)

    @property
    def residual_excess(self) -> int:
        """Return the jump budget left after the Riemann--Hurwitz minimum."""

        return self.jump_defect - self.forced_tangential_jump

    @property
    def survives_deck_rigidity(self) -> bool:
        """Whether triviality of polynomial deck symmetries keeps the passport."""

        return self.automorphism_order == 1

    @property
    def survives_contractible_branch_obstruction(self) -> bool:
        """Whether the final one-dicritical local/global filter keeps it.

        The geometric proof, external to this finite certificate, eliminates
        ``(e,d)=(2,2)`` and ``(4,1)``: their forced branch curve is
        contractible, so Lin--Zaidenberg identifies its global complement with
        the local cusp complement, contradicting the intransitive local fiber.
        """

        return (
            self.survives_deck_rigidity
            and (self.ramification_index, self.tangential_degree)
            not in {(2, 2), (4, 1)}
        )


@dataclass(frozen=True)
class OneDicriticalS6FiberProfile:
    """One target-fiber row for the surviving ``S6, (e,d)=(2,1)`` case.

    ``jumps`` contains ``kappa(t)=mu_t-2`` for the distinct normalization
    points above one target value.  It is sorted only to make the exhaustive
    table canonical; no ordering of geometric branches is intended.
    """

    jumps: tuple[int, ...]

    @property
    def boundary_block_sizes(self) -> tuple[int, ...]:
        """Return the local boundary degrees ``2 + kappa(t)``."""

        return tuple(2 + jump for jump in self.jumps)

    @property
    def affine_fiber_size(self) -> int:
        """Return the exact number of affine preimages at the target value."""

        return DEGREE - sum(self.boundary_block_sizes)

    @property
    def is_omitted(self) -> bool:
        """Whether the original affine Keller map omits the target value."""

        return self.affine_fiber_size == 0


@dataclass(frozen=True)
class S6TwoCurveFiberProfile:
    """One exact collision row in the transposition-plus-3-cycle passport."""

    event: str
    boundary_block_sizes: tuple[int, ...]

    @property
    def affine_fiber_size(self) -> int:
        """Return the affine sheets left by constant multiplicity six."""

        return DEGREE - sum(self.boundary_block_sizes)

    @property
    def is_omitted(self) -> bool:
        """Whether the boundary blocks exhaust all six sheets."""

        return self.affine_fiber_size == 0


S6_TWO_CURVE_FIBER_PROFILES: Final[tuple[S6TwoCurveFiberProfile, ...]] = (
    S6TwoCurveFiberProfile("three_cycle_self_collision", (3, 3)),
    S6TwoCurveFiberProfile("transposition_double_self_collision", (2, 2)),
    S6TwoCurveFiberProfile("transposition_triple_self_collision", (2, 2, 2)),
    S6TwoCurveFiberProfile("cross_intersection", (2, 3)),
)


@dataclass(frozen=True)
class OneDicriticalContractedSourceEndpoint:
    """Finite endpoint of the contracted-source obstruction.

    The geometry is deliberately outside this certificate.  A nontrivial
    Hirzebruch--Jung endpoint cover has no invariant linear forms.  For
    ramification index two this puts the exact Jacobian order one below the
    invariant lower bound two.  For index three, geometry further forces a
    double cover and the branch equation ``2*mu = 2 + 2*r``; deck invariance
    requires ``r`` to be odd.  This object certifies only those final integer
    incompatibilities.
    """

    ramification_index: int
    local_degree: int
    transverse_branch_contribution: int = 2
    invariant_jacobian_lower_bound: int = 2

    def __post_init__(self) -> None:
        if self.ramification_index not in (2, 3):
            msg = "the endpoint certificate only covers ramification index 2 or 3"
            raise ValueError(msg)
        if self.local_degree <= 0:
            msg = "local degree must be positive"
            raise ValueError(msg)

    @property
    def jacobian_order(self) -> int:
        """Return the exact lifted Jacobian order ``e - 1``."""

        return self.ramification_index - 1

    @property
    def contradicts_invariant_order(self) -> bool:
        """Whether the Jacobian order is below the invariant quadratic bound."""

        return self.jacobian_order < self.invariant_jacobian_lower_bound

    @property
    def cyclic_cover_order(self) -> int:
        """Return the cover order forced by the index-three quadratic jets."""

        if self.ramification_index != 3:
            msg = "the index-two case ends before a cover order is forced"
            raise ValueError(msg)
        return 2

    @property
    def lifted_degree(self) -> int:
        """Return the index-three local degree after the cyclic quotient cover."""

        return self.local_degree * self.cyclic_cover_order

    @property
    def forced_tangent_contact_order(self) -> int:
        """Solve ``lifted_degree = 2 + 2*r`` for the contact order ``r``."""

        residual = self.lifted_degree - self.transverse_branch_contribution
        if residual % 2 != 0:
            msg = "branch contributions do not determine an integral contact order"
            raise ValueError(msg)
        return residual // 2

    @property
    def contradicts_odd_deck_invariance(self) -> bool:
        """Whether index three forces an even contact under an oddness rule."""

        return (
            self.ramification_index == 3
            and self.forced_tangent_contact_order % 2 == 0
        )

    @property
    def eliminates_contracted_source(self) -> bool:
        """Whether either exact endpoint contradicts the geometric premises."""

        return (
            self.contradicts_invariant_order
            or self.contradicts_odd_deck_invariance
        )


A6_CONTRACTED_SOURCE_ENDPOINTS: Final = tuple(
    OneDicriticalContractedSourceEndpoint(
        ramification_index=3,
        local_degree=local_degree,
    )
    for local_degree in (3, 5)
)
S6_CONTRACTED_SOURCE_ENDPOINTS: Final = tuple(
    OneDicriticalContractedSourceEndpoint(
        ramification_index=2,
        local_degree=local_degree,
    )
    for local_degree in range(2, 6)
)
S6_SATURATED_CONTRACTED_SOURCE_ENDPOINTS: Final = (
    OneDicriticalContractedSourceEndpoint(
        ramification_index=2,
        local_degree=2,
    ),
    OneDicriticalContractedSourceEndpoint(
        ramification_index=3,
        local_degree=3,
    ),
)

# Backwards-compatible name for the original degree-five A6 endpoint.
A6_EXCEPTIONAL_PARITY_ENDPOINT: Final = A6_CONTRACTED_SOURCE_ENDPOINTS[-1]


@dataclass(frozen=True)
class DicriticalLeafLabelEndpoint:
    """Arithmetic endpoint of the one-dicritical leaf adjunction formula.

    On Orevkov's original pure-blowup resolution, geometry gives a type-three
    dicritical leaf of augmented-canonical label ``e`` and self-intersection
    ``-m``.  Adjunction forces its unique neighbor to have label ``e*m - 1``.
    This object records that integer relation without certifying leafhood or
    the geometric type of either curve.
    """

    ramification_index: int
    negative_self_intersection: int

    def __post_init__(self) -> None:
        if self.ramification_index < 2:
            msg = "the ramified dicritical index must be at least two"
            raise ValueError(msg)
        if self.negative_self_intersection < 1:
            msg = "the exceptional dicritical must have negative self-intersection"
            raise ValueError(msg)

    @property
    def dicritical_label(self) -> int:
        """Return the augmented-canonical label of the type-three leaf."""

        return self.ramification_index

    @property
    def neighbor_label(self) -> int:
        """Return ``e*(-E^2) - 1`` from leaf adjunction."""

        return (
            self.ramification_index * self.negative_self_intersection - 1
        )

    @property
    def has_forced_congruence(self) -> bool:
        """Whether the neighbor label is ``-1`` modulo the ramification index."""

        return (self.neighbor_label + 1) % self.ramification_index == 0

    @property
    def is_jointly_minimal(self) -> bool:
        """Whether the endpoint is the joint-minimal ``(-1)`` leaf."""

        return self.negative_self_intersection == 1

    def corner_blowup(self) -> DicriticalLeafLabelEndpoint:
        """Return the arithmetic endpoint after blowing up the leaf edge."""

        return DicriticalLeafLabelEndpoint(
            ramification_index=self.ramification_index,
            negative_self_intersection=self.negative_self_intersection + 1,
        )


A6_MINIMAL_DICRITICAL_LEAF_LABEL_ENDPOINT: Final = (
    DicriticalLeafLabelEndpoint(
        ramification_index=3,
        negative_self_intersection=1,
    )
)
S6_MINIMAL_DICRITICAL_LEAF_LABEL_ENDPOINT: Final = (
    DicriticalLeafLabelEndpoint(
        ramification_index=2,
        negative_self_intersection=1,
    )
)


def one_dicritical_s6_fiber_profiles() -> tuple[OneDicriticalS6FiberProfile, ...]:
    """Enumerate the complete finite fiber census for the ``S6`` passport.

    Orevkov gives total jump budget three.  Constant multiplicity six says
    that a target with normalization-branch jumps ``kappa_i`` has exactly
    ``6 - sum(2 + kappa_i)`` affine preimages.
    """

    result: list[OneDicriticalS6FiberProfile] = []
    for number_of_branches in range(1, DEGREE // 2 + 1):
        for jumps in combinations_with_replacement(
            range(OREVKOV_SIX_SHEET_BUDGET - 1),
            number_of_branches,
        ):
            if sum(jumps) > OREVKOV_SIX_SHEET_BUDGET - 2:
                continue
            profile = OneDicriticalS6FiberProfile(jumps=jumps)
            if profile.affine_fiber_size >= 0:
                result.append(profile)
    return tuple(
        sorted(
            result,
            key=lambda profile: (
                len(profile.jumps),
                sum(profile.jumps),
                profile.jumps,
            ),
        )
    )


@dataclass(frozen=True)
class LocalMonodromyOvergroup:
    """An overgroup normally generated by a chosen local meridian."""

    subgroup: PermutationGroup
    orbit_sizes: tuple[int, ...]

    @property
    def order(self) -> int:
        """Return the subgroup order."""

        return len(self.subgroup)


def permutation_orbit_sizes(group: PermutationGroup) -> tuple[int, ...]:
    """Return the sizes of all sheet orbits in decreasing order."""

    remaining = set(range(DEGREE))
    result: list[int] = []
    while remaining:
        point = min(remaining)
        orbit = {element[point] for element in group}
        result.append(len(orbit))
        remaining.difference_update(orbit)
    return tuple(sorted(result, reverse=True))


def normally_generated_overgroups(
    group: PermutationGroup,
    meridian: Permutation,
) -> tuple[LocalMonodromyOvergroup, ...]:
    """Enumerate overgroups normally generated by one meridian.

    A local monodromy group is such an overgroup when the *entire* local
    discriminant is one irreducible branch germ: the complement's fundamental
    group is then normally generated by a meridian.  Its sheet orbits are the
    connected local components, whose sizes are their local multiplicities.
    Merely knowing that one discriminant component is irreducible is not enough
    if another local branch is present.
    """

    if meridian not in group:
        msg = "meridian must belong to the ambient group"
        raise ValueError(msg)
    initial = generated_group((meridian,))
    overgroups = {initial}
    frontier = [initial]
    while frontier:
        subgroup = frontier.pop()
        for element in group.difference(subgroup):
            larger = generated_group((*subgroup, element))
            if larger not in overgroups:
                overgroups.add(larger)
                frontier.append(larger)

    result = tuple(
        LocalMonodromyOvergroup(
            subgroup=subgroup,
            orbit_sizes=permutation_orbit_sizes(subgroup),
        )
        for subgroup in overgroups
        if generated_group(conjugacy_class(subgroup, meridian)) == subgroup
    )
    return tuple(
        sorted(
            result,
            key=lambda analysis: (
                analysis.order,
                analysis.orbit_sizes,
                tuple(sorted(analysis.subgroup)),
            ),
        )
    )


def _contains_indices(indices: Sequence[int], required: Sequence[int]) -> bool:
    """Whether the first multiset contains the second multiset."""

    return all(
        indices.count(index) >= required.count(index)
        for index in set(required)
    )


def orevkov_budget_profiles(
    *,
    required_indices: Sequence[int] = (),
    minimum_unramified_components: int = 0,
) -> tuple[OrevkovBudgetProfile, ...]:
    """Enumerate exact degree-six profiles under Orevkov's defect identity.

    The value five is ``N-1``.  Index five is omitted because Orevkov's final
    remark excludes a dicritical component of index ``N-1`` for a Keller map.
    """

    if minimum_unramified_components < 0:
        msg = "minimum number of unramified components must be nonnegative"
        raise ValueError(msg)
    if any(
        index < 1 or index >= OREVKOV_SIX_SHEET_BUDGET
        for index in required_indices
    ):
        msg = "required indices must lie between one and four"
        raise ValueError(msg)

    result: list[OrevkovBudgetProfile] = []
    for component_count in range(1, OREVKOV_SIX_SHEET_BUDGET + 1):
        for indices in combinations_with_replacement(
            range(1, OREVKOV_SIX_SHEET_BUDGET),
            component_count,
        ):
            index_sum = sum(indices)
            if index_sum > OREVKOV_SIX_SHEET_BUDGET:
                continue
            if indices.count(1) < minimum_unramified_components:
                continue
            if not _contains_indices(indices, required_indices):
                continue
            result.append(
                OrevkovBudgetProfile(
                    dicritical_indices=indices,
                    jump_defect=OREVKOV_SIX_SHEET_BUDGET - index_sum,
                )
            )
    return tuple(result)


def fixed_point_normal_closure(group: PermutationGroup) -> PermutationGroup:
    """Return the normal subgroup generated by all fixed-point elements.

    Fixed-point elements form a union of conjugacy classes, so the subgroup
    they generate is already normal.  For a hypothetical Keller map this
    subgroup must be all of ``G``: branch meridians normally generate the
    monodromy, while every branch inertia element fixes an affine local sheet.
    The latter geometric premise is proved outside this finite calculation.
    """

    return generated_group(
        element
        for element in group
        if element != IDENTITY and has_fixed_point(element)
    )


def blocks_containing_first_point(group: PermutationGroup) -> tuple[Block, ...]:
    """Enumerate all proper non-singleton blocks containing point zero."""

    blocks: list[Block] = []
    other_points = tuple(range(1, DEGREE))
    for size in range(2, DEGREE):
        for tail in combinations(other_points, size - 1):
            block = frozenset((0, *tail))
            is_block = True
            for element in group:
                image = frozenset(element[point] for point in block)
                if image != block and not image.isdisjoint(block):
                    is_block = False
                    break
            if is_block:
                blocks.append(block)
    return tuple(blocks)


def _cosets(group: PermutationGroup, subgroup: PermutationGroup) -> tuple[PermutationGroup, ...]:
    """Return left cosets of ``subgroup`` in ``group`` in deterministic order."""

    remaining = set(group)
    result: list[PermutationGroup] = []
    while remaining:
        representative = min(remaining)
        coset = frozenset(compose(representative, member) for member in subgroup)
        result.append(coset)
        remaining.difference_update(coset)
    return tuple(result)


def quotient_structure(normalizer_group: PermutationGroup, subgroup: PermutationGroup) -> str:
    """Identify the small quotient ``normalizer_group / subgroup`` exactly."""

    cosets = _cosets(normalizer_group, subgroup)
    coset_of = {element: index for index, coset in enumerate(cosets) for element in coset}
    representatives = tuple(min(coset) for coset in cosets)
    multiplication = tuple(
        tuple(coset_of[compose(left, right)] for right in representatives)
        for left in representatives
    )
    order = len(cosets)
    if order == 1:
        return "1"
    if order in {2, 3}:
        return f"C{order}"
    if order == 6:
        abelian = all(
            multiplication[left][right] == multiplication[right][left]
            for left in range(order)
            for right in range(order)
        )
        return "C6" if abelian else "S3"
    msg = f"unexpected automorphism-group order {order}"
    raise ValueError(msg)


@dataclass(frozen=True)
class SixSheetGroupAnalysis:
    """Exact Galois-theoretic invariants of one transitive degree-six group."""

    identifier: str
    structure: str
    order: int
    stabilizer_order: int
    normalizer_order: int
    automorphism_group: str
    automorphism_order: int
    is_galois: bool
    is_primitive: bool
    block_sizes: tuple[int, ...]
    fixed_point_normal_closure_order: int
    one_dicritical_witnesses: tuple[ConjugacyClassAnalysis, ...]

    @property
    def factor_degrees(self) -> tuple[tuple[int, int], ...]:
        """Return possible ``(inner, outer)`` rational factor degrees."""

        return tuple((size, DEGREE // size) for size in self.block_sizes)

    @property
    def affine_inertia_compatible(self) -> bool:
        """Whether fixed-point inertia elements can normally generate ``G``."""

        return self.fixed_point_normal_closure_order == self.order

    @property
    def general_keller_compatible(self) -> bool:
        """Whether the proved unrestricted degree-six filters leave ``G``.

        The fixed-sheet normal-generation theorem first leaves seven groups.
        The deck/budget/local-monodromy arguments eliminate its three
        imprimitive entries.  The refined ``sum(e*d + delta) = 5`` identity
        and the irreducible-branch normalization obstruction then eliminate
        ``6T12=A5`` and ``6T14=S5``.  Those geometric arguments are proved
        outside this finite certificate.
        """

        return self.identifier in {"6T15", "6T16"}

    @property
    def one_dicritical_inertia_compatible(self) -> bool:
        """Whether one Orevkov-allowed inertia class normally generates ``G``.

        This is conditional on the one-dicritical hypothesis.  That hypothesis
        implies an irreducible nonproper curve, but the converse is not used or
        claimed: several dicritical boundary components may dominate the same
        irreducible curve.  The filter is not asserted for an arbitrary Keller
        map with several dicritical components.
        """

        return bool(self.one_dicritical_witnesses)

    @property
    def one_dicritical_keller_compatible(self) -> bool:
        """Whether the final one-dicritical filters leave a passport for ``G``.

        In the one-dicritical Keller setting, the unique boundary divisor is
        ramified and deck-invariant; purity of the affine-open boundary then
        makes every field deck transformation polynomial.  Polynomial deck
        transformations of a Keller map are trivial.  The subsequent
        Lin--Zaidenberg local/global obstruction also removes the forced
        ``(e,d)=(2,2)`` and ``(4,1)`` passports.
        """

        return any(
            passport.survives_contractible_branch_obstruction
            for passport in passports_for_analysis(self)
        )

    @property
    def one_dicritical_deck_compatible(self) -> bool:
        """Whether inertia and the intermediate deck-rigidity filter allow ``G``."""

        return (
            self.one_dicritical_inertia_compatible
            and self.automorphism_order == 1
        )


def analyze_fixture(fixture: TransitiveGroupFixture) -> SixSheetGroupAnalysis:
    """Compute all table invariants from generators, without GAP at runtime."""

    group = generated_group(fixture.generators)
    if not is_transitive(group):
        msg = f"{fixture.identifier} fixture is not transitive"
        raise ValueError(msg)
    stabilizer = point_stabilizer(group)
    normalizer_group = normalizer(group, stabilizer)
    blocks = blocks_containing_first_point(group)
    block_sizes = tuple(sorted({len(block) for block in blocks}))
    class_analyses = conjugacy_class_analyses(group)
    one_dicritical_witnesses = tuple(
        analysis
        for analysis in class_analyses
        if analysis.cycle_type in OREVKOV_ONE_DICRITICAL_TYPES
        and analysis.normal_closure_order == len(group)
    )
    return SixSheetGroupAnalysis(
        identifier=fixture.identifier,
        structure=fixture.structure,
        order=len(group),
        stabilizer_order=len(stabilizer),
        normalizer_order=len(normalizer_group),
        automorphism_group=quotient_structure(normalizer_group, stabilizer),
        automorphism_order=len(normalizer_group) // len(stabilizer),
        is_galois=normalizer_group == group,
        is_primitive=not blocks,
        block_sizes=block_sizes,
        fixed_point_normal_closure_order=len(fixed_point_normal_closure(group)),
        one_dicritical_witnesses=one_dicritical_witnesses,
    )


def classify_six_sheet_groups() -> tuple[SixSheetGroupAnalysis, ...]:
    """Analyze all sixteen GAP transitive groups of degree six."""

    return tuple(analyze_fixture(fixture) for fixture in TRANSITIVE_GROUPS)


def passports_for_analysis(
    analysis: SixSheetGroupAnalysis,
) -> tuple[OneDicriticalPassport, ...]:
    """Convert one row's normally generating inertia classes to passports."""

    result: list[OneDicriticalPassport] = []
    for inertia_class in analysis.one_dicritical_witnesses:
        nontrivial_cycles = tuple(
            length for length in inertia_class.cycle_type if length > 1
        )
        if not nontrivial_cycles or len(set(nontrivial_cycles)) != 1:
            msg = "one-dicritical inertia must consist of equal nontrivial cycles"
            raise ValueError(msg)
        ramification_index = nontrivial_cycles[0]
        result.append(
            OneDicriticalPassport(
                group_identifier=analysis.identifier,
                group_structure=analysis.structure,
                automorphism_order=analysis.automorphism_order,
                ramification_index=ramification_index,
                tangential_degree=len(nontrivial_cycles),
                jump_defect=OREVKOV_SIX_SHEET_BUDGET - ramification_index,
                inertia_class=inertia_class,
            )
        )
    return tuple(result)


def one_dicritical_passports() -> tuple[OneDicriticalPassport, ...]:
    """Return every exact passport surviving the raw one-class inertia test."""

    return tuple(
        passport
        for analysis in classify_six_sheet_groups()
        for passport in passports_for_analysis(analysis)
    )


def candidate_ids(
    *,
    non_galois: bool = True,
    primitive: bool | None = None,
    trivial_automorphisms: bool | None = None,
    affine_inertia_compatible: bool | None = None,
    general_keller_compatible: bool | None = None,
    one_dicritical_inertia_compatible: bool | None = None,
    one_dicritical_deck_compatible: bool | None = None,
    one_dicritical_keller_compatible: bool | None = None,
) -> tuple[str, ...]:
    """Filter the exact table by hypotheses, without claiming Keller realizability."""

    result: list[str] = []
    for analysis in classify_six_sheet_groups():
        if non_galois and analysis.is_galois:
            continue
        if primitive is not None and analysis.is_primitive != primitive:
            continue
        has_trivial_automorphisms = analysis.automorphism_order == 1
        if (
            trivial_automorphisms is not None
            and has_trivial_automorphisms != trivial_automorphisms
        ):
            continue
        if (
            affine_inertia_compatible is not None
            and analysis.affine_inertia_compatible != affine_inertia_compatible
        ):
            continue
        if (
            general_keller_compatible is not None
            and analysis.general_keller_compatible
            != general_keller_compatible
        ):
            continue
        if (
            one_dicritical_inertia_compatible is not None
            and analysis.one_dicritical_inertia_compatible
            != one_dicritical_inertia_compatible
        ):
            continue
        if (
            one_dicritical_deck_compatible is not None
            and analysis.one_dicritical_deck_compatible
            != one_dicritical_deck_compatible
        ):
            continue
        if (
            one_dicritical_keller_compatible is not None
            and analysis.one_dicritical_keller_compatible
            != one_dicritical_keller_compatible
        ):
            continue
        result.append(analysis.identifier)
    return tuple(result)


def _format_bool(value: bool) -> str:
    return "yes" if value else "no"


def render_table(rows: Sequence[SixSheetGroupAnalysis]) -> str:
    """Render a compact, deterministic Markdown table."""

    header = (
        "| id | G | ord(G) | ord(H) | Aut_K(L) | Galois | primitive | blocks | inertia |\n"
        "|---|---|---:|---:|---|---|---|---|---|"
    )
    body = []
    for row in rows:
        blocks = ",".join(str(size) for size in row.block_sizes) or "-"
        body.append(
            f"| {row.identifier} | {row.structure} | {row.order} | "
            f"{row.stabilizer_order} | {row.automorphism_group} | "
            f"{_format_bool(row.is_galois)} | {_format_bool(row.is_primitive)} | "
            f"{blocks} | {_format_bool(row.affine_inertia_compatible)} |"
        )
    return "\n".join((header, *body))


def main() -> int:
    """Print the exact classification and the principal surviving filters."""

    rows = classify_six_sheet_groups()
    print(render_table(rows))
    print()
    print("non-Galois:", ", ".join(candidate_ids()))
    print(
        "non-Galois + trivial Aut_K(L):",
        ", ".join(candidate_ids(trivial_automorphisms=True)),
    )
    print(
        "non-Galois + primitive:",
        ", ".join(candidate_ids(primitive=True)),
    )
    print(
        "non-Galois + affine-inertia compatible:",
        ", ".join(candidate_ids(affine_inertia_compatible=True)),
    )
    print(
        "unrestricted final compatible:",
        ", ".join(candidate_ids(general_keller_compatible=True)),
    )
    print(
        "non-Galois + one-dicritical inertia compatible:",
        ", ".join(candidate_ids(one_dicritical_inertia_compatible=True)),
    )
    print(
        "one-dicritical deck compatible:",
        ", ".join(
            candidate_ids(
                one_dicritical_deck_compatible=True,
            )
        ),
    )
    print(
        "one-dicritical final compatible:",
        ", ".join(
            candidate_ids(
                one_dicritical_keller_compatible=True,
            )
        ),
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
